services:

  db:
    image: postgres:latest
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    
  webapp:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db

  todo_nginx_proxy:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp

volumes:
  db_data:
    